version: "3.0"
services:
  web:
    build: ./web
    container_name: python
    ports:
      - "5000:5000"
    volumes:
      - ./web:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  dbdata:
